### ISSUE TITLE
Feature 10: User can view favorite eateries.

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/final-project#10]
## ⚙️ Feature

The user can navigate to the Favorites page where they can see their favorite eateries.

## 📐 Functionality

The user can access the Favorites page via the menu or navigation bar.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/46775983/200422643-77416daa-10a9-4ee4-bb33-0ac526b7c63b.png)
![image](https://user-images.githubusercontent.com/46775983/200422761-f38e3778-f31e-45a6-8848-dfcacf8e29dd.png)

### ☁️ Server Tasks

- [x] Add a (GET) middleware function to index.js.
  - [x] Set the route to "/favorites"
  - [x] Add an SQL (SELECT/JOIN) statement for "favorites" and "restaurants" tables.
  - [x] Add an array for query parameters with "accountId" hard coded.
  - [x] Add a query method.
  - [x] On success, send a 200 status and response to the client.
  - [x] On failure, point to errorMiddleware.
- [x] Test and troubleshoot database response.

### ⚡ Client Tasks

**Phase 1 - Update navigation/hash routing and add Favorites page.**
- [x] Update the Nav class.
  - [x] Add a link to the Favorites page.
  - [x] Ensure the href attribute has a value of "#favorites".
  - [x] Ensure the component renders properly on mobile and desktop.
- [x] Update the App class.
  - [x] Import the Favorites component (non-existent for now).
  - [x] In the renderPage method, check for the "favorites" path.
  - [x] Ensure the Favorites component is returned from the method.
- [x] Create a new file named "favorites.jsx" in the pages folder.
  - [x] Add a class named Favorites as a default export.
  - [x] Add a constructor function.
  - [x] Add a state named "inFavorites" initialized as an empty array.
  - [x] Add a componentDidMount method.
  - [x] Add a (GET) fetch function to the server using the "/favorites" route.
  - [x] Store the response in the inFavorites state.
- [x] Add a render function.
  - [x] Render an empty Div react element (for now).
- [x] Test and troubleshoot navigation and server response.

**Phase 2 - Render roulette items on the Roulette page.**
- [x] Update favorites.jsx.
   - [x] Import the ResultCard component. 
- [x] Update the render function in the Favorites class.
  - [x] Add a map method that renders ResultCards using the inFavorites state.
  - [x] Render the return of the method in the return expression.
  - [x] Ensure the ResultCard components render properly on mobile and desktop.
- [x] Update the Favorites class.
  - [x] Add and bind a prototype method named "removeFromFavorites".
- [x] Update the removeFromFavorites method.
  - [x] Copy/Paste the same method from the SearchResults class.
- [x] Test and troubleshoot removing favorite items.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
