### ISSUE TITLE
Feature 6: User can view roulette.

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/final-project#6]
## ⚙️ Feature

The user can navigate to the Roulette page where they can see the roulette wheel and any eateries added to the roulette.

## 📐 Functionality

The user can access the Roulette page via the menu or navigation bar.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/46775983/200420349-0a6db7c9-b96b-4947-b86f-d1396ebe6654.png)
![image](https://user-images.githubusercontent.com/46775983/200408685-1366ad3d-9bfb-4fb2-ab9a-938412f4917a.png)

### ☁️ Server Tasks

- [x] Add a (GET) middleware function to index.js.
  - [x] Set the route to "/roulette"
  - [x] Add an SQL (SELECT/JOIN) statement for "roulette" and "restaurants" tables.
  - [x] Add an array for query parameters with "accountId" hard coded.
  - [x] Add a query method.
  - [x] On success, send a 200 status and response to the client.
  - [x] On failure, point to errorMiddleware.
- [x] Test and troubleshoot database response.

### ⚡ Client Tasks

**Phase 1 - Update navigation/hash routing and add Roulette page.**
- [x] Update the Nav class.
  - [x] Add a link to the Roulette page.
  - [x] Ensure the href attribute has a value of "#roulette".
  - [x] Ensure the component renders properly on mobile and desktop.
- [x] Update the App class.
  - [x] Import the Roulette component (non-existent for now).
  - [x] In the renderPage method, check for the "roulette" path.
  - [x] Ensure the Roulette component is returned from the method.
- [x] Create a new file named "roulette.jsx" in the pages folder.
  - [x] Add a class named Roulette as a default export.
  - [x] Add a constructor function.
  - [x] Add a state named "inRoulette" initialized as an empty array.
  - [x] Add a componentDidMount method.
  - [x] Add a (GET) fetch function to the server using the "/roulette" route.
  - [x] Store the response in the inRoulette state.
- [x] Add a render function.
  - [x] Render an empty Div react element (for now).
- [x] Test and troubleshoot navigation and server response.

**Phase 2 - Render roulette items on the Roulette page.**
- [x] Update roulette.jsx.
   - [x] Import the ResultCard component. 
- [x] Update the render function in the Roulette class.
  - [x] Add a map method that renders ResultCards using the inRoulette state.
  - [x] Render the return of the method in the return expression.
  - [x] Ensure the ResultCard components render properly on mobile and desktop.
- [x] Update the Roulette class.
  - [x] Add and bind a prototype method named "removeFromRoulette".
- [x] Update the removeFromRoulette method.
  - [x] Copy/Paste the same method from the SearchResults class.
- [x] Test and troubleshoot removing roulette items.

**Phase 3 - Render roulette wheel.**
- [x] Import "react-roulette-pro".
- [x] Update the render function in roulette.jsx.
  - [x] Import the Spinner component (non-existent for now). 
  - [x] Add a map method to prepare an array of roulette item objects.
  - [x] Ensure the objects contain an eatery's thumbnail and name.
  - [x] Add a conditional statement checking for at least 2 roulette items.
  - [x] Return the Spinner component if true.
  - [x] Return null if not.
  - [x] Ensure the array of roulette item objects are passed into Spinner as a prop.
  - [x] Render the return in the return expression.
- [x] Create a new file named "spinner.jsx" in the components folder.
  - [x] Import RoulettePro from react-roulette-pro. 
  - [x] Add a function named Spinner.
  - [x] Ensure the function is a default export.
  - [x] Return the RoulettePro component.
  - [x] Add a helper function named "prepareSpinner" with a parameter for an array.
- [x] Update the prepareSpinner helper function.
  - [x] "Extend" the array passed in.
  - [x] Add a unique ID to the extended array.
  - [x] Calculate a winner using the indexes of the extended array.
  - [x] Return the extended array and winner.
 - [x] Update the RoulettePro component.
   - [x] Pass in the extended array using the prop "prizes".
   - [x] Pass in the winning index using the prop "prizeindex". 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
